const fs = require("fs");
let list1 = JSON.parse(fs.readFileSync("map10.json", "utf-8"));
list1 = list1.objects.map10.geometries.map((it) => ({
  ...it.properties,
}));
list1 = Object.fromEntries(list1.map((item) => [item.ISO_CC, item]));
console.log(list1);

const data = [
  {
    code: "ALB",
    con: "Albania",
    po: 2745972,
    mb: 87.71,
    au: 4090,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-albanii.html",
  },
  {
    code: "DZA",
    con: "Algieria",
    po: 45606480,
    mb: 66.98,
    au: 29094,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-algierii.html",
  },
  {
    code: "ARG",
    con: "Argentina",
    po: 46654581,
    mb: 77.47,
    au: 87208,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-argentynie.html",
  },
  {
    code: "AUS",
    con: "Australia",
    po: 26638544,
    mb: 91.38,
    au: 63817,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-australii.html",
  },
  {
    code: "AUT",
    con: "Austria",
    po: 9132383,
    mb: 93,
    au: 43381,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-austrii.html",
  },
  {
    code: "AZE",
    con: "Azerbejdżan",
    po: 10112555,
    mb: 78,
    au: 7178,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-azerbejdzanie.html",
  },
  {
    code: "BHS",
    con: "Bahamas",
    po: 412623,
    mb: 82,
    au: 2350,
    url: "https://tgmresearch.com/online-panel-in-bahamas.html",
  },
  {
    code: "BHR",
    con: "Bahrajn",
    po: 1485509,
    mb: 83.87,
    au: 3856,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-bahrajnie.html",
  },
  {
    code: "BGD",
    con: "Bangladesz",
    po: 172954319,
    mb: 59.03,
    au: 74572,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-bangladeszu.html",
  },
  {
    code: "BEL",
    con: "Belgia",
    po: 11822592,
    mb: 92.97,
    au: 42600,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-belgii.html",
  },
  {
    code: "BOL",
    con: "Boliwia",
    po: 12388571,
    mb: 61.76,
    au: 13116,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-boliwii.html",
  },
  {
    code: "BIH",
    con: "Bośnia i Hercegowina",
    po: 3210847,
    mb: 76.24,
    au: 12421,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-bosni-i-hercegowinie.html",
  },
  {
    code: "BWA",
    con: "Botswana",
    po: 2675352,
    mb: 52.37,
    au: 20167,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-botswanie.html",
  },
  {
    code: "BRA",
    con: "Brazylia",
    po: 216422446,
    mb: 73.74,
    au: 356056,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-brazylii.html",
  },
  {
    code: "BRN",
    con: "Brunei",
    po: 452524,
    mb: 70.06,
    au: 2259,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-brunei.html",
  },
  {
    code: "BGR",
    con: "Bułgaria",
    po: 6430370,
    mb: 81.66,
    au: 42233,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-bulgarii.html",
  },
  {
    code: "KHM",
    con: "Kambodża",
    po: 16944826,
    mb: 63.11,
    au: 6516,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kambodzy.html",
  },
  {
    code: "CMR",
    con: "Kamerun",
    po: 28647293,
    mb: 47.41,
    au: 32791,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kamerunie.html",
  },
  {
    code: "CAN",
    con: "Kanada",
    po: 40097761,
    mb: 89.22,
    au: 87695,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kanadzie.html",
  },
  {
    code: "CHL",
    con: "Chile",
    po: 19629590,
    mb: 77.81,
    au: 52126,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-chile.html",
  },
  {
    code: "CHN",
    con: "Chiny",
    po: 1410710000,
    mb: 87.91,
    au: 153114,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-chinach.html",
  },
  {
    code: "COL",
    con: "Kolumbia",
    po: 52085168,
    mb: 71.19,
    au: 165023,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kolumbii.html",
  },
  {
    code: "CRI",
    con: "Kostaryka",
    po: 5212173,
    mb: 76.53,
    au: 10104,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-kostaryce.html",
  },
  {
    code: "HRV",
    con: "Chorwacja",
    po: 3853200,
    mb: 79.04,
    au: 26030,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-chorwacji.html",
  },
  {
    code: "CYP",
    con: "Cyprus",
    po: 1260138,
    mb: 90.83,
    au: 2832,
    url: "https://tgmresearch.com/online-panel-in-cyprus.html",
  },
  {
    code: "CZE",
    con: "Republika Czeska",
    po: 10873689,
    mb: 93.3,
    au: 64029,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-czechach.html",
  },
  {
    code: "DNK",
    con: "Dania",
    po: 5946952,
    mb: 93.5,
    au: 23286,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-danii.html",
  },
  {
    code: "DOM",
    con: "Republika Dominikany",
    po: 11332972,
    mb: 76.01,
    au: 15971,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-dominikanie.html",
  },
  {
    code: "ECU",
    con: "Ekwador",
    po: 18190484,
    mb: 66.87,
    au: 20576,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-ekwadorze.html",
  },
  {
    code: "EGY",
    con: "Egipt",
    po: 112716598,
    mb: 69.06,
    au: 73782,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-egipcie.html",
  },
  {
    code: "SLV",
    con: "Zbawiciel",
    po: 6364943,
    mb: 54.5,
    au: 12124,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-salwadorze.html",
  },
  {
    code: "EST",
    con: "Estonia",
    po: 1366188,
    mb: 84.78,
    au: 11052,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-estonii.html",
  },
  {
    code: "ETH",
    con: "Etiopia",
    po: 126527060,
    mb: 33.66,
    au: 38386,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-etiopii.html",
  },
  {
    code: "FIN",
    con: "Finlandia",
    po: 5584264,
    mb: 92.72,
    au: 42848,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-finlandii.html",
  },
  {
    code: "FRA",
    con: "Francja",
    po: 68170228,
    mb: 95.78,
    au: 179818,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-we-francji.html",
  },
  {
    code: "GEO",
    con: "Gruzja",
    po: 3760365,
    mb: 80.84,
    au: 8086,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-gruzji.html",
  },
  {
    code: "GHA",
    con: "Ghana",
    po: 34121985,
    mb: 55.49,
    au: 96670,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-ghanie.html",
  },
  {
    code: "GRC",
    con: "Grecja",
    po: 10361295,
    mb: 93.46,
    au: 35088,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-grecji.html",
  },
  {
    code: "GTM",
    con: "Gwatemala",
    po: 17602431,
    mb: 50.86,
    au: 5041,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-gwatemali.html",
  },
  {
    code: "HND",
    con: "Honduras",
    po: 10593798,
    mb: 48.66,
    au: 5055,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-hondurasie.html",
  },
  {
    code: "HKG",
    con: "Hongkong",
    po: 7536100,
    mb: 96.56,
    au: 17188,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-hong-kongu.html",
  },
  {
    code: "HUN",
    con: "Węgry",
    po: 9589872,
    mb: 85.2,
    au: 50800,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-wegrzech.html",
  },
  {
    code: "ISL",
    con: "Islandia",
    po: 393600,
    mb: 81.41,
    au: 2964,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-islandii.html",
  },
  {
    code: "IND",
    con: "Indie",
    po: 1428627663,
    mb: 65.21,
    au: 357717,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-indiach.html",
  },
  {
    code: "IDN",
    con: "Indonezja",
    po: 277534122,
    mb: 58.04,
    au: 271175,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-indonezji.html",
  },
  {
    code: "IRL",
    con: "Irlandia",
    po: 5262382,
    mb: 85.82,
    au: 13824,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-irlandii.html",
  },
  {
    code: "ISR",
    con: "Izrael",
    po: 9756700,
    mb: 80.09,
    au: 17523,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-izraelu.html",
  },
  {
    code: "ITA",
    con: "Włochy",
    po: 58761146,
    mb: 93.98,
    au: 156035,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-we-wloszech.html",
  },
  {
    code: "CIV",
    con: "Wybrzeże Kości Słoniowej",
    po: 28873034,
    mb: 50.1,
    au: 16280,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-wybrzezu-kosci-sloniowej.html",
  },
  {
    code: "JAM",
    con: "Jamaica",
    po: 2825544,
    mb: 75.19,
    au: 3485,
    url: "https://tgmresearch.com/online-panel-in-jamaica.html",
  },
  {
    code: "JPN",
    con: "Japonia",
    po: 124516650,
    mb: 90.91,
    au: 205370,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-japonii.html",
  },
  {
    code: "JOR",
    con: "Jordania",
    po: 11337052,
    mb: 74.35,
    au: 8550,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-jordanii.html",
  },
  {
    code: "KAZ",
    con: "Kazachstan",
    po: 19900177,
    mb: 60.01,
    au: 17720,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kazachstanie.html",
  },
  {
    code: "KEN",
    con: "Kenia",
    po: 55100586,
    mb: 57.61,
    au: 211139,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kenii.html",
  },
  {
    code: "KWT",
    con: "Kuwejt",
    po: 4310108,
    mb: 93.87,
    au: 3082,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-kuwejcie.html",
  },
  {
    code: "LAO",
    con: "Laos",
    po: 7633779,
    mb: 56.67,
    au: 4121,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-laosie.html",
  },
  {
    code: "LTU",
    con: "Litwa",
    po: 2871897,
    mb: 87.84,
    au: 38017,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-litwie.html",
  },
  {
    code: "LUX",
    con: "Luxembourg",
    po: 668606,
    mb: 91.87,
    au: 2790,
    url: "https://tgmresearch.com/online-panel-in-luxembourg.html",
  },
  {
    code: "MYS",
    con: "Malezja",
    po: 34308525,
    mb: 79.99,
    au: 78161,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-malezji.html",
  },
  {
    code: "MLT",
    con: "Malta",
    po: 553214,
    mb: 73.41,
    au: 2815,
    url: "https://tgmresearch.com/online-panel-in-malta.html",
  },
  {
    code: "MEX",
    con: "Meksyk",
    po: 128455567,
    mb: 78.27,
    au: 157274,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-meksyku.html",
  },
  {
    code: "MDA",
    con: "Moldova",
    po: 2486891,
    mb: 100,
    au: 10709,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-moldawii.html",
  },
  {
    code: "MNG",
    con: "Mongolia",
    po: 3447157,
    mb: 80.86,
    au: 4468,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-mongolii.html",
  },
  {
    code: "MNE",
    con: "Czarnogóra",
    po: 616177,
    mb: 81.25,
    au: 3133,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-czarnogorze.html",
  },
  {
    code: "MAR",
    con: "Maroko",
    po: 37840044,
    mb: 71.11,
    au: 88458,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-maroku.html",
  },
  {
    code: "MOZ",
    con: "Mozambik",
    po: 33897354,
    mb: 39.62,
    au: 9568,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-mozambiku.html",
  },
  {
    code: "MMR",
    con: "Myanmar",
    po: 54577997,
    mb: 58.32,
    au: 17137,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-birmie.html",
  },
  {
    code: "NAM",
    con: "Namibia",
    po: 2604172,
    mb: 41.03,
    au: 14800,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-namibii.html",
  },
  {
    code: "NPL",
    con: "Nepal",
    po: 30896590,
    mb: 71.14,
    au: 7663,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-nepalu.html",
  },
  {
    code: "NLD",
    con: "Holandia",
    po: 17879488,
    mb: 91.12,
    au: 42554,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-holandii.html",
  },
  {
    code: "NZL",
    con: "Nowa Zelandia",
    po: 5223100,
    mb: 86.46,
    au: 16888,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-nowej-zelandii.html",
  },
  {
    code: "NIC",
    con: "Nikaragua",
    po: 7046310,
    mb: 54.05,
    au: 9805,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-nikaragui.html",
  },
  {
    code: "NGA",
    con: "Nigeria",
    po: 223804632,
    mb: 48.47,
    au: 249523,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-nigerii.html",
  },
  {
    code: "MKD",
    con: "Macedonia Północna",
    po: 1811980,
    mb: 74.74,
    au: 3905,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-macedonii-polnocnej.html",
  },
  {
    code: "NOR",
    con: "Norwegia",
    po: 5519594,
    mb: 89.05,
    au: 17412,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-norwegii.html",
  },
  {
    code: "OMN",
    con: "Oman",
    po: 4644384,
    mb: 90.76,
    au: 5374,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-omanie.html",
  },
  {
    code: "PAK",
    con: "Pakistan",
    po: 240485658,
    mb: 40.4,
    au: 278343,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-pakistanie.html",
  },
  {
    code: "PSE",
    con: "Palestyna",
    po: 5044000,
    mb: 0,
    au: 2975,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-palestynie.html",
  },
  {
    code: "PAN",
    con: "Panama",
    po: 4468087,
    mb: 85.31,
    au: 7048,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-panamie.html",
  },
  {
    code: "PRY",
    con: "Paragwaj",
    po: 6861524,
    mb: 73.92,
    au: 8673,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-paragwaju.html",
  },
  {
    code: "PER",
    con: "Peru",
    po: 34352719,
    mb: 67.5,
    au: 40709,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-peru.html",
  },
  {
    code: "PHL",
    con: "Filipiny",
    po: 117337368,
    mb: 55.76,
    au: 279396,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-filipinach.html",
  },
  {
    code: "POL",
    con: "Polska",
    po: 36685849,
    mb: 74.55,
    au: 152185,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-polsce.html",
  },
  {
    code: "PRT",
    con: "Portugalia",
    po: 10525347,
    mb: 93.51,
    au: 98822,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-portugalii.html",
  },
  {
    code: "PRI",
    con: "Portoryko",
    po: 3205691,
    mb: 0,
    au: 3065,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-portoryko.html",
  },
  {
    code: "QAT",
    con: "Katar",
    po: 2716391,
    mb: 100,
    au: 4254,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-katarze.html",
  },
  {
    code: "ROU",
    con: "Rumunia",
    po: 19056116,
    mb: 77.88,
    au: 145609,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-rumunii.html",
  },
  {
    code: "RWA",
    con: "Rwanda",
    po: 14094683,
    mb: 47.84,
    au: 11962,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-rwandzie.html",
  },
  {
    code: "SAU",
    con: "Arabia Saudyjska (KSA)",
    po: 36947025,
    mb: 77.19,
    au: 53032,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-arabii-saudyjskiej-ksa.html",
  },
  {
    code: "SEN",
    con: "Senegal",
    po: 17763163,
    mb: 45.99,
    au: 11163,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-senegalu.html",
  },
  {
    code: "SRB",
    con: "Serbia",
    po: 6618026,
    mb: 100,
    au: 35326,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-serbii.html",
  },
  {
    code: "SGP",
    con: "Singapur",
    po: 5917648,
    mb: 93.99,
    au: 32442,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-singapurze.html",
  },
  {
    code: "SVK",
    con: "Słowacja",
    po: 5426740,
    mb: 84.65,
    au: 38256,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-slowacji.html",
  },
  {
    code: "SVN",
    con: "Słowenia",
    po: 2120937,
    mb: 89.87,
    au: 16322,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-slowenii.html",
  },
  {
    code: "ZAF",
    con: "Afryka Południowa",
    po: 60414495,
    mb: 77.07,
    au: 167445,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-afryce-poludniowej.html",
  },
  {
    code: "KOR",
    con: "Korea Południowa",
    po: 51712619,
    mb: 95.11,
    au: 73795,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-korei-poludniowej.html",
  },
  {
    code: "ESP",
    con: "Hiszpania",
    po: 48373336,
    mb: 94.66,
    au: 153696,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-hiszpanii.html",
  },
  {
    code: "LKA",
    con: "Sri Lanka",
    po: 22037000,
    mb: 62.28,
    au: 34089,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-sri-lance.html",
  },
  {
    code: "SWE",
    con: "Szwecja",
    po: 10536632,
    mb: 91.99,
    au: 88064,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-szwecji.html",
  },
  {
    code: "CHE",
    con: "Szwajcaria",
    po: 8849852,
    mb: 94.22,
    au: 22163,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-szwajcarii.html",
  },
  {
    code: "TWN",
    con: "Tajwan",
    po: 23420000,
    mb: 0,
    au: 21096,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-tajwanie.html",
  },
  {
    code: "TZA",
    con: "Tanzania",
    po: 67438106,
    mb: 47.53,
    au: 14109,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-tanzanii.html",
  },
  {
    code: "THA",
    con: "Tajlandia",
    po: 71801279,
    mb: 77.02,
    au: 86261,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-tajlandii.html",
  },
  {
    code: "TTO",
    con: "Trinidad and Tobago",
    po: 1534937,
    mb: 68.31,
    au: 3200,
    url: "https://tgmresearch.com/online-panel-in-trinidad-and-tobago.html",
  },
  {
    code: "TUN",
    con: "Tunezja",
    po: 12458223,
    mb: 73.92,
    au: 13491,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-tunezji.html",
  },
  {
    code: "TUR",
    con: "Turcja",
    po: 85326000,
    mb: 78.51,
    au: 79964,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-turcji.html",
  },
  {
    code: "TKM",
    con: "Turkmenia",
    po: 6516100,
    mb: 0,
    au: 4974,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-turkmenistanie.html",
  },
  {
    code: "UGA",
    con: "Uganda",
    po: 48582334,
    mb: 45.65,
    au: 52490,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-ugandzie.html",
  },
  {
    code: "GBR",
    con: "Wielka Brytania (UK)",
    po: 68350000,
    mb: 92.3,
    au: 185052,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-wielkiej-brytanii-uk.html",
  },
  {
    code: "UKR",
    con: "Ukraina",
    po: 37000000,
    mb: 85.71,
    au: 194642,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-ukrainie.html",
  },
  {
    code: "ARE",
    con: "Zjednoczone Emiraty Arabskie (ZEA)",
    po: 9516871,
    mb: 92.87,
    au: 31432,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-zjednoczonych-emiratach-arabskich-zea.html",
  },
  {
    code: "USA",
    con: "Stany Zjednoczone (USA)",
    po: 334914895,
    mb: 90.93,
    au: 373479,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-stanach-zjednoczonych-usa.html",
  },
  {
    code: "URY",
    con: "Urugwaj",
    po: 3423108,
    mb: 79.87,
    au: 8271,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-urugwaju.html",
  },
  {
    code: "UZB",
    con: "Uzbekistan",
    po: 36412350,
    mb: 60.55,
    au: 9452,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-uzbekistanie.html",
  },
  {
    code: "VNM",
    con: "Wietnam",
    po: 98858950,
    mb: 64.4,
    au: 53761,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-wietnamie.html",
  },
  {
    code: "ZMB",
    con: "Zambia",
    po: 20569737,
    mb: 41.36,
    au: 29935,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-zambii.html",
  },
  {
    code: "DEU",
    con: "Niemcy",
    po: 84482267,
    mb: 92.1,
    au: 182442,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-w-niemczech.html",
  },
  {
    code: "LVA",
    con: "Łotwa",
    po: 1881750,
    mb: 90.69,
    au: 13671,
    url: "https://tgmresearch.pl/panel-online-badania-rynku-na-lotwie.html",
  },
];

const missing = [];
data.forEach((it) => {
  if (!list1[it.code]) {
    missing.push(it);
  }
});

fs.writeFileSync(`missing.json`, JSON.stringify(missing, null, 2), "utf8");
